docs/AboutUs.md
docs/UserGuide.md
docs/index.md

Update AboutUs, UserGuide, Index.md to reflect team information

docs: init documentation

---

docs/AboutUs.md

limit the width of profile photo so it does not grow automatically

AboutUs.md: adjust the size of profile photo

---

README.md
docs/_config.yml

Update AboutUs.md and config.yml to reflect project details and information

docs: update user documentation

---

src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/PersonListCard.fxml

The person card now displays NRIC, name and sex for person. NRIC and sex information are currently set to static strings, will update when Person class is ready. Same goes for status icon.

Update Person Card

---

.github/workflows/gradle_notest.yml

Gradle Workflow without checking for test cases

Create a CI workflow with no test

---

src/main/resources/view/CommandBox.fxml
src/main/resources/view/PersonListCard.fxml

Fix commandbox colour

---

src/main/resources/view/PersonListCard.fxml

Adjust person card size to be bigger and padded texts to fit bigger person card panel.

Fix person card size to fit new main window size

---

src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/BloodType.java
src/main/java/seedu/address/model/person/Person.java

Add optional field setters, key words and and parsers

---

src/main/java/seedu/address/model/person/Status.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/PersonListCard.fxml

Initial set up for such, may need some edits later after Json is adapted.

Update nric, sex and status circle

---

src/main/java/seedu/address/model/person/BloodType.java
src/main/java/seedu/address/model/person/DateOfBirth.java
src/main/java/seedu/address/model/person/Nric.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Implemented for email, country, allergies, blood type, condition, date of admission, diagnosis and sympton.

Update JsonAdaptedPerson for optional fields

---

src/main/java/seedu/address/logic/parser/ParserUtil.java
src/test/java/seedu/address/testutil/PersonBuilder.java

Optional Fields were added into JsonAdaptedPerson which resulted in Null Exception due to incorrect handling of Null Values. 
Temporarily removed Optional Fields from test cases
Updated ParserUtil.java for incorrect method names

fix: Remove optional fields from Test

---

src/main/java/seedu/address/logic/commands/ReadCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/ReadCommandParser.java
src/main/java/seedu/address/model/person/NricContainsKeywordsPredicate.java

Add initial read command. Requires updates after subsequent merges for other features. Need to implement tests on a later time. Included predicate of NIRC for reference, should be included prior to merging this.

Add read command

---

src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/commands/UpdateCommand.java
src/main/java/seedu/address/model/person/Person.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java

CommandTestUtil: Change blood type to single string
Person.java: fix equal() to include all fields to make sure equal() implies identical copies

Fix miscellaneous details

---

src/main/java/seedu/address/logic/commands/ReadCommand.java

Change argument to hasPerson to Person.createPersonWithNric

---

src/main/java/seedu/address/logic/commands/ReadCommand.java
src/main/java/seedu/address/logic/parser/ReadCommandParser.java
src/test/java/seedu/address/logic/commands/ReadCommandTest.java
src/test/java/seedu/address/logic/parser/ReadCommandParserTest.java

Tests for some methods. Will add more.

Add tests for some methods in ReadCommand and ReadCommandParser

---

docs/diagrams/ModelClassDiagram.puml

Update ModelClass diagram to Include new Optional Variables

docs: update ModelClass diagram

---

build.gradle
src/main/java/seedu/address/logic/commands/ReadCommand.java
src/main/java/seedu/address/logic/parser/ReadCommandParser.java

Fix command for scenarios in which nric is wrong or not given. Edit shadow jar name.

Fix read command parser and read command exceptions 

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/ReadCommand.java
src/main/java/seedu/address/logic/parser/ReadCommandParser.java
src/main/resources/view/MainWindow.fxml
src/test/java/seedu/address/logic/parser/ReadCommandParserTest.java

New read format message. Updated some read command and main window.

Fix messages format for display of read command

---

src/test/java/seedu/address/logic/commands/ReadCommandTest.java
src/test/java/seedu/address/logic/parser/ReadCommandParserTest.java

Completed all tests for read command.

Add all tests for ReadCommand and ReadCommandParser

---

build.gradle

Enable Assertions in build gradle

feat: enable assertions

---

src/test/java/seedu/address/logic/LogicManagerTest.java

All test cases are now passing

Fix remaining testcases

---

src/main/java/seedu/address/ui/CommandBox.java

CommandHistory stores previous commands in a LinkedList. Users can then navigate the History using their numpad

Add CommandHistory feature to CommandBox

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/CheckCommand.java
src/main/java/seedu/address/logic/parser/CheckCommandParser.java
src/main/java/seedu/address/logic/parser/ImmuniMateParser.java
src/main/java/seedu/address/model/visit/VisitContainsNricPredicate.java

Add check command for history. Tests to be added later.

Add check command

---

docs/UserGuide.md

Add new FAQs for Patient Visit not updating Patient Information, Name not accepting weird characters, inability to add multiple patient visits

Update FAQ in UG

---

src/main/resources/view/MainWindow.fxml

Remove ImmuniMate Button due to incomplete feature

Remove immunimate button

---

docs/UserGuide.md

Add on for read command in complement to Lanyu's changes to UG.

Update read and check command examples in UG 
